### PR TITLE
Fix session commands

### LINKED ISSUE #125: Add session command accepts trailing characters
`session add gibberish` adds a session even though there are invalid arguments.

### LINKED ISSUE #126: Usage message of AddSessionCommand is never shown
Users may not be able to learn how to use it. This is linked to #125, since the command parameters are all optional.

### LINKED ISSUE #127: EditSessionCommand executes when there are no fields provided

### LINKED ISSUE #128: Error when parsing an invalid date or time
Parsing an invalid date or time causes a runtime exception that exits the program.

### LINKED ISSUE #129: Error when parsing an invalid index in edit session command
Parsing an invalid index (i.e. not a valid number) in EditSessionCommandParser causes a runtime exception that exits the program.

### PR DESCRIPTION
**Pull request by PotatoCombat**
# Summary

There were some issues when testing the session commands:

# Bugs
- #125 : Add session command accepts trailing characters 
- #126 : Usage message of AddSessionCommand is never shown 
- #127 : EditSessionCommand executes when there are no fields provided
- #128 : Error when parsing an invalid date or time
- #129 : Error when parsing an invalid index in edit session command

# Fixes and Suggestions
#125 , #126 : Fixed by ensuring no trailing characters. However, an alternative is to make the start time a compulsory prefix.

#127 : Fixed by ensuring at least one field is being edited. However this conflicts with a comment in EditSessionCommandParser by @Eclmist.

#128 , #129 : Fixed by raising a ParseException.

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/AddSessionCommand.java [hunk 1]
```diff
@@ -15,19 +18,24 @@
  */
 public class AddSessionCommand extends Command {
 
-    public static final String COMMAND_WORD = "Session";
+    public static final String COMMAND_WORD = CommandWords.SESSION + " " + CommandWords.ADD_MODEL;
 
-    public static final String MESSAGE_USAGE = COMMAND_WORD + ": Adds a session to the TATracker. "
+    public static final String MESSAGE_USAGE = COMMAND_WORD + ": Adds a session in TA-Tracker. "
```
Comment (aakanksha-rai) [inline src/main/java/seedu/address/logic/commands/AddSessionCommand.java:23]: I think even the old message was fine. New one is also fine lol

File: src/main/java/seedu/address/model/session/Session.java [hunk 2]
```diff
@@ -169,6 +173,18 @@ public Duration getSessionDuration() {
...
+    public String toString() {
+        final StringBuilder builder = new StringBuilder();
+        builder.append("Type: ").append(type)
+                .append(" Start: ").append(startDateTime.format(FORMAT_DATE_TIME))
+                .append(" End: ").append(endDateTime.format(FORMAT_DATE_TIME))
+                .append(" Module Code: ").append(moduleCode)
+                .append(" Description: ").append(description)
+                .append(" Recurs: ").append(isRecurring);
+        return builder.toString();
+    }
```
Comment (aakanksha-rai) [inline src/main/java/seedu/address/model/session/Session.java:186]: The string message is actually quite long. Not all of it is visible in the line. Would be a good idea to add some new lines (\n).

**Review by aakanksha-rai — APPROVED** [review]
Just need to change toString(). Other than that, looks good to me!

File: src/main/java/seedu/address/logic/commands/AddSessionCommand.java (hunk 1 above)
Comment (PotatoCombat) [reply src/main/java/seedu/address/logic/commands/AddSessionCommand.java:23]: Oh its just for the hyphen!

File: src/main/java/seedu/address/model/session/Session.java (hunk 2 above)
Comment (PotatoCombat) [reply src/main/java/seedu/address/model/session/Session.java:186]: No problem! I actually have an idea of how to make this part of my user visible feature. Instead of printing a message, it'll show all the info in a ui card in the result box.
