### PR TITLE
Fix session edit

### LINKED ISSUE #273: [PE-D] Session edit command can receive empty argument
Currently, the `session edit` command allows the user to provided empty argument e.g. `session edit 1`. It is better to have a check similar to `student edit` command that checks that at least one parameter must be edited to maintain consistency.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: mario7lorenzo/ped#18

### PR DESCRIPTION
**Pull request by chuayijing**

### CODE REVIEW

File: src/main/java/tatracker/logic/parser/session/EditSessionCommandParser.java [hunk 1]
```diff
@@ -78,6 +78,8 @@ public EditSessionCommand parse(String args) throws ParseException {
 
         if (argMultimap.getValue(RECUR).isPresent()) {
             editSessionDescriptor.setRecurring(ParserUtil.parseNumWeeks(argMultimap.getValue(RECUR).get()));
+        } else {
+            editSessionDescriptor.setRecurring(-1);
         }
```
Comment (PotatoCombat) [inline src/main/java/tatracker/logic/parser/session/EditSessionCommandParser.java]: No need this. If its not recurring don't need to change the default value.

File: src/main/java/tatracker/model/session/Session.java [hunk 2]
```diff
@@ -30,7 +30,7 @@
     public Session() {
         this.startDateTime = LocalDateTime.now();
         this.endDateTime = LocalDateTime.now();
-        this.recurring = 0;
+        this.recurring = -1;
```
Comment (PotatoCombat) [inline src/main/java/tatracker/model/session/Session.java]: Maybe have -1 as a private constant? Like NO_RECURRING_VALUE

File: src/main/java/tatracker/logic/parser/session/EditSessionCommandParser.java [hunk 3]
```diff
@@ -96,8 +98,10 @@ public EditSessionCommand parse(String args) throws ParseException {
 
         // TODO: Check if editing should be allowed if there are no fields
         if (!editSessionDescriptor.isAnyFieldEdited()) {
+            System.out.println("here");
```
Comment (PotatoCombat) [inline src/main/java/tatracker/logic/parser/session/EditSessionCommandParser.java]: Careful with logging!

File: src/main/java/tatracker/logic/commands/session/EditSessionCommand.java [hunk 4]
```diff
@@ -191,11 +194,11 @@ public void setEndTime(LocalDateTime endTime) {
...
 
         public void setRecurring(int isRecurring) {
-            this.isRecurring = isRecurring;
+            this.newRecurring = isRecurring;
         }
 
-        public int getRecurring() {
-            return this.isRecurring;
+        public Optional<Integer> getRecurring() {
+            return Optional.ofNullable(newRecurring);
```
Comment (PotatoCombat) [inline src/main/java/tatracker/logic/commands/session/EditSessionCommand.java]: Hmm no you would need to do:

if newRecurring < 0 return Optional.empty
else return Optional.of(newRecurring)

File: src/main/java/tatracker/logic/commands/session/EditSessionCommand.java [hunk 5]
```diff
@@ -170,8 +170,11 @@ public EditSessionDescriptor(EditSessionDescriptor toCopy) {
          * Returns true if at least one field is edited.
          */
         public boolean isAnyFieldEdited() {
-            return isDateChanged || CollectionUtil.isAnyNonNull(newStartTime, newEndTime,
-                    newModuleCode, newDescription, newSessionType, isRecurring);
+            boolean dateChanged = isDateChanged;
+            boolean recurringChanged = (newRecurring == -1);
```
Comment (PotatoCombat) [inline src/main/java/tatracker/logic/commands/session/EditSessionCommand.java]: recurring changed = newRecurring >= 0

File: src/main/java/tatracker/logic/commands/session/EditSessionCommand.java [hunk 6]
```diff
@@ -170,8 +170,11 @@ public EditSessionDescriptor(EditSessionDescriptor toCopy) {
...
+            boolean otherVariables = CollectionUtil.isAnyNonNull(newStartTime, newEndTime,
+                    newModuleCode, newDescription, newSessionType);
+            return dateChanged || otherVariables || !recurringChanged;
```
Comment (PotatoCombat) [inline src/main/java/tatracker/logic/commands/session/EditSessionCommand.java]: recurringChanged

File: src/main/java/tatracker/ui/sessiontab/SessionCard.java [hunk 7]
```diff
@@ -57,7 +57,7 @@ public SessionCard(Session session, int displayedIndex) {
                 + session.getEndDateTime().format(timeFormat));
         module.setText(session.getModuleCode().toUpperCase());
         description.setText(session.getDescription());
-        if (session.getRecurring() != 0) {
+        if (session.getRecurring() != -1) {
```
Comment (PotatoCombat) [inline src/main/java/tatracker/ui/sessiontab/SessionCard.java]: session getRecurring > 0 is correct!
The -1 is for the editing only

**Review by PotatoCombat — APPROVED** [review]
LGTM! Thanks!
