### PR TITLE
Fix bugs from PE Dry-Run

### LINKED ISSUE #250: [PE-D] Small typo in UG; 'Claims vieww', but its very minor
-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: nathanaelseen/ped#6

### LINKED ISSUE #251: [PE-D] module filter m/MOD_CODE under the claims view/tab, yields an unknown command
-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: nathanaelseen/ped#5

### LINKED ISSUE #253: [PE-D] Module name is not updated everywhere (after module edit command to edit its name)
First, (I was in 'Student' tab) and I created a new module with name; 'AI', and then I edited the module's name to 'Programming';

Next, I navigate to 'Claims' tab, but the module was still named 'Programming', instead of 'AI';

(Update: the bug seems to be resolved after application is restarted.)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: nathanaelseen/ped#3

### LINKED ISSUE #256: [PE-D] Total Claimable Hours
I could not find any documentation for statistics, so I am unsure of how total claimable hours is calculated. But it appears that the pay per hour is assumed to be a certain number. Maybe the user could be given a choice to enter the pay themselves, since he/she could be earning different wages per hour for different modules/tutorials.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: souwmyaa/ped#13

### LINKED ISSUE #260: [PE-D] Inconsistency in User Guide
The example and the format are conflicting. One says id/ and the other says m/ for matriculation number. I think it could be confusing to the user!

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: souwmyaa/ped#9

### LINKED ISSUE #261: [PE-D] Spelling error in User Guide
View is spelt wrong in this part!

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: souwmyaa/ped#8

### LINKED ISSUE #264: [PE-D] Module filter does not work
User Guide claims that module filter m/[MODULE_NAME] is a valid command.

However, I did not observe the functionality when I tried it!

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: souwmyaa/ped#5

### LINKED ISSUE #293: [PE-D] [TA] Default statistics view hides most of the data
Resizing is required to see the words. Also text color could be improved to improve readibility of some text.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: umaikaze/ped#6

### LINKED ISSUE #304: [PE-D] Unknown command for set rate
-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: ZhangYiping126/ped#10

### LINKED ISSUE #305: [PE-D] Statistics format error
No labels for pie chart and table cannot be seen, also the student table cannot display for more than 5 students.

Maybe it is because it is still in working process given that it is not included in UG, so the severity is set to be very low.

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: ZhangYiping126/ped#9

### PR DESCRIPTION
**Pull request by fatin99**

### CODE REVIEW

File: src/main/java/tatracker/logic/parser/ParserUtil.java [hunk 1]
```diff
@@ -288,4 +288,19 @@ public static Tab parseTabName(String tabName) throws ParseException {
...
+             if (parsedRate <= 0) {
+                 throw new ParseException("RATE must be a positive integer");
+             }
+             System.out.println("Parse Rate:" + parsedRate);
+             return parsedRate;
+         } catch (NumberFormatException e) {
+             throw new ParseException("RATE must be a positive integer");
+        }
+    }
 }
```
Comment (PotatoCombat) [inline src/main/java/tatracker/logic/parser/ParserUtil.java]: There's a parse unsigned integer function alr. Can reuse that in this function, but catch and throw another exception with the new messages.

Also careful with debugging

Comment (PotatoCombat) [reply src/main/java/tatracker/logic/parser/ParserUtil.java]: I can parse +1 and it will be valid.

File: src/main/java/tatracker/logic/parser/commons/SetRateCommandParser.java [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+
+    /**
+     * Parses the given {@code String} of arguments in the context of the SetRateCommand
+     * and returns a SetRateCommand object for execution.
+     * @throws ParseException if the user input does not conform the expected format
+     */
+    public SetRateCommand parse(String args) throws ParseException {
+        try {
+            int rate = ParserUtil.parseRate(args);
+            System.out.println("return new SetRateCommand:" + rate);
```
Comment (PotatoCombat) [inline src/main/java/tatracker/logic/parser/commons/SetRateCommandParser.java]: Log

File: src/main/java/tatracker/model/TaTracker.java [hunk 3]
```diff
@@ -41,7 +41,7 @@
     private static Module currentlyShownModule;
     private static Module currentlyShownModuleClaim;
 
-    private int rate;
+    private static int rate;
```
Comment (PotatoCombat) [inline src/main/java/tatracker/model/TaTracker.java]: This shouldn't be static I reckon.

File: src/main/java/tatracker/logic/commands/commons/SetRateCommand.java [hunk 4]
```diff
@@ -19,7 +19,7 @@
 
     public static final CommandDetails DETAILS = new CommandDetails(
             CommandWords.SET_RATE,
-            "Sets the pay rate to the specified integer.",
+            "Sets the pay rate to a specified integer greater than zero.",
             List.of(),
             List.of()
```
Comment (PotatoCombat) [inline src/main/java/tatracker/logic/commands/commons/SetRateCommand.java]: Need to add the prefix parameters in here. See other commands

File: src/main/java/tatracker/ui/MainWindow.java [hunk 5]
```diff
@@ -257,7 +257,7 @@ public void handleStatistic(String moduleCode) {
         }
 
         // Create a new statistic window
-        statisticWindow = new StatisticWindow(new Statistic(logic.getTaTracker(), moduleCode), logic.getGuiSettings());
+        statisticWindow = new StatisticWindow(new Statistic(logic.getTaTracker(), moduleCode), logic.getGuiSettings(), logic.getTaTracker());
```
Comment (PotatoCombat) [inline src/main/java/tatracker/ui/MainWindow.java]: Doesn't Statistic have a tatracker already?

File: src/main/java/tatracker/ui/StatisticWindow.java [hunk 6]
```diff
@@ -111,7 +115,7 @@ public StatisticWindow(Stage root, Statistic stats, GuiSettings guiSettings) {
         numHoursGradingLabel.setText(stats.numHoursPerCategory[3] + " Hours");
         numHoursPreparationLabel.setText(stats.numHoursPerCategory[4] + " Hours");
         numHoursOtherLabel.setText(stats.numHoursPerCategory[5] + " Hours");
-        numHoursTotalLabel.setText(stats.getTotalHours() + " (S$" + stats.getTotalPay() + ")");
+        numHoursTotalLabel.setText(taTracker.getTotalHours() + " (S$" + taTracker.getTotalEarnings() + ")");
```
Comment (PotatoCombat) [inline src/main/java/tatracker/ui/StatisticWindow.java]: Should leave as stats.get

File: src/main/java/tatracker/logic/parser/ParserUtil.java [hunk 7]
```diff
@@ -303,14 +304,12 @@ public static int parseRate(String rate) throws ParseException {
...
-                throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT,
-                        SetRateCommand.DETAILS.getUsage()));
+            if (!StringUtil.isNonZeroUnsignedInteger(trimmedRate)) {
+                throw new ParseException(MESSAGE_INVALID_RATE);
             }
-            System.out.println("Parse Rate:" + parsedRate);
             return parsedRate;
         } catch (NumberFormatException e) {
-            throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT, SetRateCommand.DETAILS.getUsage()));
+            throw new ParseException(MESSAGE_INVALID_RATE);
```
Comment (PotatoCombat) [inline src/main/java/tatracker/logic/parser/ParserUtil.java]: Yup! That's the idea

File: src/main/java/tatracker/logic/parser/commons/SetRateCommandParser.java [hunk 8]
```diff
@@ -23,13 +23,9 @@
...
     public SetRateCommand parse(String args) throws ParseException {
-        try {
-            int rate = ParserUtil.parseRate(args);
-            System.out.println("return new SetRateCommand:" + rate);
-            return new SetRateCommand(rate);
-        } catch (ParseException pe) {
-            throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT, SetRateCommand.DETAILS.getUsage()));
-        }
+        int rate = ParserUtil.parseRate(args);
+        System.out.println("return new SetRateCommand:" + rate);
```
Comment (PotatoCombat) [inline src/main/java/tatracker/logic/parser/commons/SetRateCommandParser.java]: Log

File: src/main/java/tatracker/logic/commands/commons/SetRateCommand.java [hunk 9]
```diff
@@ -0,0 +1,40 @@
...
+
+/**
+ * Switches between tabs
+ */
+public class SetRateCommand extends Command {
+
+    public static final CommandDetails DETAILS = new CommandDetails(
+            CommandWords.SET_RATE,
+            "Sets the pay rate to a specified integer greater than zero.",
+            List.of(),
```
Comment (PotatoCombat) [inline src/main/java/tatracker/logic/commands/commons/SetRateCommand.java:23]: Can add the RATE prefix in here? Thanks

File: src/main/java/tatracker/logic/commands/commons/SetRateCommand.java [hunk 10]
```diff
@@ -0,0 +1,40 @@
+package tatracker.logic.commands.commons;
+
+import static tatracker.model.TaTracker.setRate;
```
Comment (PotatoCombat) [inline src/main/java/tatracker/logic/commands/commons/SetRateCommand.java]: set rate should not be a static method I reckon

File: src/main/java/tatracker/logic/parser/commons/SetRateCommandParser.java [hunk 11]
```diff
@@ -0,0 +1,36 @@
...
+public class SetRateCommandParser implements Parser<SetRateCommand> {
+
+    /**
+     * Parses the given {@code String} of arguments in the context of the SetRateCommand
+     * and returns a SetRateCommand object for execution.
+     * @throws ParseException if the user input does not conform the expected format
+     */
+    public SetRateCommand parse(String args) throws ParseException {
+        int rate = ParserUtil.parseRate(args);
+        System.out.println("return new SetRateCommand:" + rate);
```
Comment (PotatoCombat) [inline src/main/java/tatracker/logic/parser/commons/SetRateCommandParser.java]: Careful with logging

File: src/main/java/tatracker/model/TaTracker.java (hunk 3 above)
Comment (PotatoCombat) [inline src/main/java/tatracker/model/TaTracker.java]: This should not be a static variable I reckon

File: src/main/java/tatracker/model/TaTracker.java [hunk 12]
```diff
@@ -223,8 +223,9 @@ public int getRate() {
         return rate;
     }
 
-    public void setRate(int rate) {
-        this.rate = rate;
+    public static void setRate(int newRate) {
+        System.out.println("Reached SetRate in TaTracker");
+        rate = newRate;
```
Comment (PotatoCombat) [inline src/main/java/tatracker/model/TaTracker.java]: This should be a instance method, not a static one.

also logging

File: src/main/java/tatracker/ui/MainWindow.java [hunk 13]
```diff
@@ -257,7 +257,8 @@ public void handleStatistic(String moduleCode) {
         }
 
         // Create a new statistic window
-        statisticWindow = new StatisticWindow(new Statistic(logic.getTaTracker(), moduleCode), logic.getGuiSettings());
+        statisticWindow = new StatisticWindow(new Statistic(logic.getTaTracker(), moduleCode), logic.getGuiSettings(),
+                logic.getTaTracker());
```
Comment (PotatoCombat) [inline src/main/java/tatracker/ui/MainWindow.java]: Doesn't Statistic already have a taTracker?

File: src/main/java/tatracker/ui/StatisticWindow.java [hunk 14]
```diff
@@ -111,7 +109,7 @@ public StatisticWindow(Stage root, Statistic stats, GuiSettings guiSettings) {
         numHoursGradingLabel.setText(stats.numHoursPerCategory[3] + " Hours");
         numHoursPreparationLabel.setText(stats.numHoursPerCategory[4] + " Hours");
         numHoursOtherLabel.setText(stats.numHoursPerCategory[5] + " Hours");
-        numHoursTotalLabel.setText(stats.getTotalHours() + " (S$" + stats.getTotalPay() + ")");
```
Comment (PotatoCombat) [inline src/main/java/tatracker/ui/StatisticWindow.java:114]: I think better to leave this as stats.get

File: src/main/java/tatracker/ui/StatisticWindow.java [hunk 15]
```diff
@@ -138,8 +136,8 @@ public void handle(KeyEvent t) {
     /**
      * Creates a new HelpWindow.
      */
-    public StatisticWindow(Statistic stats, GuiSettings guiSettings) {
-        this(new Stage(), stats, guiSettings);
+    public StatisticWindow(Statistic stats, GuiSettings guiSettings, ReadOnlyTaTracker taTracker) {
+        this(new Stage(), stats, guiSettings, taTracker);
```
Comment (PotatoCombat) [inline src/main/java/tatracker/ui/StatisticWindow.java]: Same

File: src/main/java/tatracker/ui/StatisticWindow.java [hunk 16]
```diff
@@ -111,7 +109,7 @@ public StatisticWindow(Stage root, Statistic stats, GuiSettings guiSettings) {
         numHoursGradingLabel.setText(stats.numHoursPerCategory[3] + " Hours");
         numHoursPreparationLabel.setText(stats.numHoursPerCategory[4] + " Hours");
         numHoursOtherLabel.setText(stats.numHoursPerCategory[5] + " Hours");
-        numHoursTotalLabel.setText(stats.getTotalHours() + " (S$" + stats.getTotalPay() + ")");
+        numHoursTotalLabel.setText(taTracker.getTotalHours() + " (S$" + taTracker.getTotalEarnings() + ")");
```
Comment (PotatoCombat) [inline src/main/java/tatracker/ui/StatisticWindow.java]: Same

**Review by PotatoCombat — COMMENTED** [review]
Set rate should not be static I reckon
Careful with logging. Nearing end of project so wld be good to change them to logging!

File: src/main/java/tatracker/logic/commands/commons/SetRateCommand.java (hunk 9 above)
Comment (PotatoCombat) [reply src/main/java/tatracker/logic/commands/commons/SetRateCommand.java:23]: Will fix in sep PR

File: src/main/java/tatracker/logic/parser/ParserUtil.java [hunk 17]
```diff
@@ -288,4 +289,30 @@ public static Tab parseTabName(String tabName) throws ParseException {
...
+     *
+     * @param rate user input
+     * @return the pay rate specified by the user
+     * @throws ParseException invalid pay rate
+     */
+    public static int parseRate(String rate) throws ParseException {
+        requireNonNull(rate);
+        String trimmedRate = rate.trim();
+
+        if (!StringUtil.isUnsignedInteger(trimmedRate)) {
```
Comment (PotatoCombat) [inline src/main/java/tatracker/logic/parser/ParserUtil.java:304]: String util has a non zero unsigned integer? So no need the following try catch?

Comment (PotatoCombat) [reply src/main/java/tatracker/logic/parser/ParserUtil.java:304]: I thot this was alright just now?

Comment (PotatoCombat) [reply src/main/java/tatracker/logic/parser/ParserUtil.java:304]: No my bad this is correct

**Review by PotatoCombat — APPROVED** [review]
LGTM!
